CREATE DATABASE IF NOT EXISTS Causes DEFAULT CHARACTER SET utf8;

use Causes;

CREATE TABLE TB_ROLES
(
	ID INT auto_increment PRIMARY KEY,
	ROLE_NAME VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO TB_ROLES(ROLE_NAME) 
VALUES
 ('User'),
 ('Admin');

 CREATE TABLE TB_USERS
 (
	ID INT auto_increment PRIMARY KEY,
	USER_ID VARCHAR(25) NOT NULL UNIQUE,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(128) NOT NULL,
	PASSWORD_SALT VARCHAR(128) NOT NULL,
	CREATED_DATE DATETIME,
	LAST_LOGIN_DATE DATETIME,
	ROLE_ID INT,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	DISPLAY_NAME VARCHAR(100) NOT NULL,
    CONSTRAINT `FK_UsersRoleId_TBRoles_Id` FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLES (ID) ON DELETE CASCADE
 );

CREATE TABLE TB_CAUSES
(
	ID INT auto_increment PRIMARY KEY,
	TOPIC VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	IMG_URL VARCHAR(250),
	CREATED_BY INT NOT NULL,
	CREATED_DATE DATETIME,
    CONSTRAINT `FK_CausesCreatedBy_TBUsers_Id` FOREIGN KEY (CREATED_BY) REFERENCES TB_USERS (ID) ON DELETE CASCADE
);

CREATE TABLE TB_SIGNATURES
(
	ID INT auto_increment PRIMARY KEY,
	CAUSE_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	SIGNED_DATE DATETIME,
    CONSTRAINT `FK_SignaturesCauseId_TBCauses_Id` FOREIGN KEY (CAUSE_ID) REFERENCES TB_CAUSES (ID) ON DELETE CASCADE,
    CONSTRAINT `FK_SignaturesUserId_TBUsers_Id` FOREIGN KEY (USER_ID) REFERENCES TB_USERS (ID) ON DELETE CASCADE
);